// frontend/app/super-admin/businesses/new/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Save, Copy, Eye, EyeOff, Check } from 'lucide-react'
import toast from 'react-hot-toast'
import Link from 'next/link'
import { getBusinessUrl, getDisplayDomain, formatBusinessUrlForDisplay, isProduction } from '@/lib/domain-helper'

interface CreatedBusinessResult {
  business: any
  admin: {
    id: number
    email: string
    firstName: string
    lastName: string
    temporaryPassword: string
  }
}

export default function NewBusinessPage() {
  const router = useRouter()
  const [saving, setSaving] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const [createdResult, setCreatedResult] = useState<CreatedBusinessResult | null>(null)
  const [formData, setFormData] = useState({
    slug: '',
    businessName: '',
    businessType: 'food',
    phone: '',
    whatsappNumber: '',
    email: '',
    address: '',
    description: '',
    primaryColor: '#10B981',
    secondaryColor: '#F59E0B',
    currency: 'NGN',
    language: 'en',
    adminEmail: '',
    adminFirstName: '',
    adminLastName: '',
    adminPhone: ''
  })

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setSaving(true)

    try {
      const response = await fetch('/api/business', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify(formData),
      })

      if (!response.ok) {
        const error = await response.json()
        throw new Error(error.error || 'Failed to create business')
      }

      const data = await response.json()
      
      if (data.ok && data.admin && data.admin.temporaryPassword) {
        setCreatedResult(data)
        toast.success('Business and admin account created successfully!')
      } else {
        toast.success('Business created successfully!')
        router.push('/platform/dashboard')
      }
    } catch (error: any) {
      toast.error(error.message)
    } finally {
      setSaving(false)
    }
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setFormData(prev => ({
      ...prev,
      [e.target.name]: e.target.value
    }))
  }

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text)
    toast.success(`${label} copied to clipboard`)
  }

  const copyAllCredentials = () => {
    if (!createdResult) return
    
    const { displayUrl, actualUrl, protocol } = formatBusinessUrlForDisplay(createdResult.business.slug)
    const showBothUrls = !isProduction()
    
    const credentials = `
Business Created Successfully!
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Business Name: ${createdResult.business.businessName}
Business URL: ${protocol}://${displayUrl}
${showBothUrls ? `(Development URL: ${protocol}://${actualUrl})` : ''}

Admin Login Credentials:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Email: ${createdResult.admin.email}
Temporary Password: ${createdResult.admin.temporaryPassword}

⚠️ IMPORTANT INSTRUCTIONS:
1. Visit your business dashboard at the URL above
2. Login with the credentials provided
3. IMMEDIATELY change your password after first login
4. You can create additional staff and admin users
5. Keep these credentials secure

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by MyPadiFood Platform
`.trim()

    navigator.clipboard.writeText(credentials)
    toast.success('All credentials copied to clipboard!')
  }

  if (createdResult) {
    const { displayUrl, actualUrl, protocol } = formatBusinessUrlForDisplay(createdResult.business.slug)
    const businessUrl = getBusinessUrl(createdResult.business.slug)
    
    return (
      <div className="min-h-screen bg-gradient-to-br from-green-50 to-emerald-50 py-12">
        <div className="max-w-3xl mx-auto px-4">
          <div className="bg-white rounded-2xl shadow-2xl overflow-hidden">
            <div className="bg-gradient-to-r from-green-500 to-emerald-600 p-8 text-white text-center">
              <div className="w-20 h-20 bg-white rounded-full flex items-center justify-center mx-auto mb-4">
                <Check className="w-12 h-12 text-green-600" />
              </div>
              <h1 className="text-3xl font-bold mb-2">Business Created Successfully!</h1>
              <p className="text-green-100">Admin account has been set up with temporary credentials</p>
            </div>

            <div className="p-8 space-y-6">
              <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded-r-lg">
                <div className="flex items-start">
                  <div className="flex-shrink-0">
                    <svg className="h-5 w-5 text-yellow-400" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <div className="ml-3">
                    <h3 className="text-sm font-medium text-yellow-800">Important Security Notice</h3>
                    <p className="mt-1 text-sm text-yellow-700">
                      These credentials will only be shown ONCE. Please copy and securely share them with the business owner.
                    </p>
                  </div>
                </div>
              </div>

              <div className="bg-blue-50 rounded-lg p-6">
                <h2 className="text-lg font-semibold text-gray-900 mb-4">Business Information</h2>
                <div className="space-y-3">
                  <div className="flex justify-between items-center">
                    <span className="text-gray-600">Business Name:</span>
                    <span className="font-medium text-gray-900">{createdResult.business.businessName}</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-gray-600">Business URL:</span>
                    <div className="flex items-center space-x-2">
                      <code className="bg-white px-3 py-1 rounded text-sm">
                        {displayUrl}
                      </code>
                      <button
                        onClick={() => copyToClipboard(`${protocol}://${displayUrl}`, 'URL')}
                        className="p-2 hover:bg-blue-100 rounded transition-colors"
                      >
                        <Copy className="w-4 h-4 text-blue-600" />
                      </button>
                    </div>
                  </div>
                  {!isProduction() && (
                    <div className="flex justify-between items-center">
                      <span className="text-gray-600 text-xs">Dev URL:</span>
                      <code className="bg-white px-3 py-1 rounded text-xs text-gray-500">
                        {actualUrl}
                      </code>
                    </div>
                  )}
                </div>
              </div>

              <div className="bg-green-50 rounded-lg p-6 border-2 border-green-200">
                <h2 className="text-lg font-semibold text-gray-900 mb-4">Admin Login Credentials</h2>
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Email Address</label>
                    <div className="flex items-center space-x-2">
                      <input
                        type="text"
                        readOnly
                        value={createdResult.admin.email}
                        className="flex-1 px-4 py-2 bg-white border border-gray-300 rounded-lg font-mono"
                      />
                      <button
                        onClick={() => copyToClipboard(createdResult.admin.email, 'Email')}
                        className="p-2 bg-green-100 hover:bg-green-200 rounded-lg transition-colors"
                      >
                        <Copy className="w-5 h-5 text-green-600" />
                      </button>
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Temporary Password</label>
                    <div className="flex items-center space-x-2">
                      <input
                        type={showPassword ? 'text' : 'password'}
                        readOnly
                        value={createdResult.admin.temporaryPassword}
                        className="flex-1 px-4 py-2 bg-white border border-gray-300 rounded-lg font-mono"
                      />
                      <button
                        onClick={() => setShowPassword(!showPassword)}
                        className="p-2 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors"
                      >
                        {showPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
                      </button>
                      <button
                        onClick={() => copyToClipboard(createdResult.admin.temporaryPassword, 'Password')}
                        className="p-2 bg-green-100 hover:bg-green-200 rounded-lg transition-colors"
                      >
                        <Copy className="w-5 h-5 text-green-600" />
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              <div className="bg-gray-50 rounded-lg p-6">
                <h2 className="text-lg font-semibold text-gray-900 mb-4">Instructions for Business Owner</h2>
                <ol className="space-y-2 text-sm text-gray-700 list-decimal list-inside">
                  <li>Visit your business dashboard at the URL provided above</li>
                  <li>Login using the email and temporary password</li>
                  <li><strong className="text-red-600">IMMEDIATELY change your password</strong> after first login</li>
                  <li>You can create additional staff and admin users from your dashboard</li>
                  <li>Configure your business settings, add products, and start selling!</li>
                </ol>
              </div>

              <div className="flex flex-col sm:flex-row gap-3 pt-6 border-t">
                <button
                  onClick={copyAllCredentials}
                  className="flex-1 flex items-center justify-center space-x-2 px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium"
                >
                  <Copy className="w-5 h-5" />
                  <span>Copy All Credentials</span>
                </button>
                <button
                  onClick={() => window.open(businessUrl, '_blank')}
                  className="flex-1 px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors font-medium"
                >
                  Open Business Dashboard
                </button>
                <button
                  onClick={() => router.push('/platform/dashboard')}
                  className="px-6 py-3 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-colors font-medium"
                >
                  Back to Platform
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }

  // Get display domain for the slug input suffix
  const displayDomainSuffix = getDisplayDomain('', true).replace(/^\./, '') || 'mypadifood.com'

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4">
        <div className="flex items-center space-x-4 mb-6">
          <Link href="/platform/dashboard" className="p-2 hover:bg-gray-200 rounded-lg">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Create New Business</h1>
            <p className="text-gray-600">Set up a new tenant with admin account</p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="bg-white rounded-xl shadow p-8 space-y-8">
          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-4 pb-2 border-b">Business Information</h2>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Subdomain (Slug) *
                </label>
                <div className="flex items-center">
                  <input
                    type="text"
                    name="slug"
                    value={formData.slug}
                    onChange={handleChange}
                    required
                    pattern="[a-z0-9-]+"
                    placeholder="chrenisfarm"
                    className="flex-1 px-4 py-2 border border-gray-300 rounded-l-lg focus:ring-2 focus:ring-blue-500"
                  />
                  <span className="px-4 py-2 bg-gray-100 border border-l-0 border-gray-300 rounded-r-lg text-gray-600">
                    .{displayDomainSuffix}
                  </span>
                </div>
                <p className="text-sm text-gray-500 mt-1">Only lowercase letters, numbers, and hyphens</p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Business Name *
                </label>
                <input
                  type="text"
                  name="businessName"
                  value={formData.businessName}
                  onChange={handleChange}
                  required
                  placeholder="Chrenis Farm"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Business Type
                </label>
                
                <select
                  name="businessType"
                  value={formData.businessType}
                  onChange={handleChange}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Select Business Type</option>
                  
                  {/* Food & Dining */}
                  <optgroup label="🍽️ Food & Dining">
                    <option value="food">Food & Groceries</option>
                    <option value="restaurant">Restaurant</option>
                    <option value="bakery">Bakery & Pastries</option>
                    <option value="cafe">Cafe & Coffee Shop</option>
                    <option value="fastfood">Fast Food</option>
                    <option value="catering">Catering Services</option>
                  </optgroup>
                  
                  {/* Agriculture & Farming */}
                  <optgroup label="🌾 Agriculture & Farming">
                    <option value="farming">Farm Produce & Livestock</option>
                    <option value="agriculture">Agriculture & Crops</option>
                    <option value="livestock">Livestock & Poultry</option>
                    <option value="fishery">Fishery & Aquaculture</option>
                    <option value="dairy">Dairy Products</option>
                    <option value="organic">Organic Produce</option>
                  </optgroup>
                  
                  {/* Hospitality */}
                  <optgroup label="🏨 Hospitality">
                    <option value="hotel">Hotel</option>
                    <option value="shortlet">Shortlet</option>
                  </optgroup>
                  
                  {/* Retail & Shopping */}
                  <optgroup label="🛍️ Retail & Shopping">
                    <option value="retail">Retail Store</option>
                    <option value="supermarket">Supermarket</option>
                    <option value="fashion">Fashion & Clothing</option>
                    <option value="boutique">Boutique</option>
                    <option value="jewelry">Jewelry & Accessories</option>
                    <option value="toys">Toys & Games</option>
                    <option value="pets">Pet Shop & Supplies</option>
                  </optgroup>
                  
                  {/* Technology & Electronics */}
                  <optgroup label="💻 Technology & Electronics">
                    <option value="electronics">Electronics</option>
                    <option value="phones">Phone & Gadgets</option>
                    <option value="computers">Computers & IT</option>
                    <option value="software">Software & Tech</option>
                    <option value="telecommunications">Telecommunications</option>
                  </optgroup>
                  
                  {/* Health & Beauty */}
                  <optgroup label="💄 Health & Beauty">
                    <option value="beauty">Beauty & Cosmetics</option>
                    <option value="pharmacy">Pharmacy & Health</option>
                    <option value="gym">Gym & Fitness Center</option>
                    <option value="spa">Spa & Wellness</option>
                    <option value="clinic">Clinic & Medical</option>
                    <option value="dental">Dental Clinic</option>
                  </optgroup>
                  
                  {/* Home & Living */}
                  <optgroup label="🏠 Home & Living">
                    <option value="furniture">Furniture</option>
                    <option value="realestate">Real Estate</option>
                    <option value="construction">Construction & Building</option>
                    <option value="plumbing">Plumbing Services</option>
                    <option value="electrical">Electrical Services</option>
                    <option value="cleaning">Cleaning Services</option>
                    <option value="florist">Florist & Garden</option>
                  </optgroup>
                  
                  {/* Automotive */}
                  <optgroup label="🚗 Automotive">
                    <option value="automotive">Automotive & Parts</option>
                    <option value="carwash">Car Wash & Detailing</option>
                  </optgroup>
                  
                  {/* Education & Learning */}
                  <optgroup label="🎓 Education & Learning">
                    <option value="education">Education & Training</option>
                    <option value="bookstore">Books & Stationery</option>
                    <option value="daycare">Daycare & Nursery</option>
                  </optgroup>
                  
                  {/* Sports & Recreation */}
                  <optgroup label="⚽ Sports & Recreation">
                    <option value="sports">Sports & Fitness</option>
                    <option value="entertainment">Entertainment</option>
                  </optgroup>
                  
                  {/* Professional Services */}
                  <optgroup label="💼 Professional Services">
                    <option value="services">Services</option>
                    <option value="consulting">Consulting</option>
                    <option value="legal">Legal Services</option>
                    <option value="accounting">Accounting & Finance</option>
                    <option value="events">Event Planning</option>
                    <option value="photography">Photography Studio</option>
                  </optgroup>
                  
                  {/* Other Services */}
                  <optgroup label="🔧 Other Services">
                    <option value="laundry">Laundry & Dry Cleaning</option>
                    <option value="logistics">Logistics & Delivery</option>
                    <option value="printing">Printing Services</option>
                    <option value="artcraft">Arts & Crafts</option>
                  </optgroup>
                  
                  <option value="other">Other</option>
                </select>
              </div>

              <div className="grid md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Phone Number *
                  </label>
                  <input
                    type="tel"
                    name="phone"
                    value={formData.phone}
                    onChange={handleChange}
                    required
                    placeholder="+234 811 025 2143"
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    WhatsApp Number *
                  </label>
                  <input
                    type="tel"
                    name="whatsappNumber"
                    value={formData.whatsappNumber}
                    onChange={handleChange}
                    required
                    placeholder="2348110252143"
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Email
                  </label>
                  <input
                    type="email"
                    name="email"
                    value={formData.email}
                    onChange={handleChange}
                    placeholder="contact@business.com"
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Address
                  </label>
                  <input
                    type="text"
                    name="address"
                    value={formData.address}
                    onChange={handleChange}
                    placeholder="123 Business Street, Lagos"
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Description
                </label>
                <textarea
                  name="description"
                  value={formData.description}
                  onChange={handleChange}
                  rows={3}
                  placeholder="Brief description of the business..."
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Primary Color
                  </label>
                  <input
                    type="color"
                    name="primaryColor"
                    value={formData.primaryColor}
                    onChange={handleChange}
                    className="w-full h-12 px-2 border border-gray-300 rounded-lg"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Secondary Color
                  </label>
                  <input
                    type="color"
                    name="secondaryColor"
                    value={formData.secondaryColor}
                    onChange={handleChange}
                    className="w-full h-12 px-2 border border-gray-300 rounded-lg"
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Currency
                  </label>
                  <select
                    name="currency"
                    value={formData.currency}
                    onChange={handleChange}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="NGN">Nigerian Naira (₦)</option>
                    <option value="USD">US Dollar ($)</option>
                    <option value="GBP">British Pound (£)</option>
                    <option value="EUR">Euro (€)</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Default Language
                  </label>
                  <select
                    name="language"
                    value={formData.language}
                    onChange={handleChange}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="en">English</option>
                    <option value="yo">Yoruba</option>
                    <option value="ig">Igbo</option>
                    <option value="ha">Hausa</option>
                    <option value="fr">French</option>
                  </select>
                </div>
              </div>
            </div>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-gray-900 mb-4 pb-2 border-b">Admin Account (Business Owner)</h2>
            <p className="text-sm text-gray-600 mb-4">
              This account will be created as the primary administrator for the business. 
              A temporary password will be generated automatically.
            </p>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Admin Email Address * <span className="text-xs text-gray-500">(This will be the login email)</span>
                </label>
                <input
                  type="email"
                  name="adminEmail"
                  value={formData.adminEmail}
                  onChange={handleChange}
                  required
                  placeholder="owner@business.com"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div className="grid md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    First Name
                  </label>
                  <input
                    type="text"
                    name="adminFirstName"
                    value={formData.adminFirstName}
                    onChange={handleChange}
                    placeholder="John"
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Last Name
                  </label>
                  <input
                    type="text"
                    name="adminLastName"
                    value={formData.adminLastName}
                    onChange={handleChange}
                    placeholder="Doe"
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Admin Phone
                </label>
                <input
                  type="tel"
                  name="adminPhone"
                  value={formData.adminPhone}
                  onChange={handleChange}
                  placeholder="+234 800 000 0000"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <p className="text-sm text-blue-800">
                  <strong>Note:</strong> A secure temporary password will be automatically generated 
                  and shown to you after creation. The business owner must change this password on first login.
                </p>
              </div>
            </div>
          </div>

          <div className="flex justify-end space-x-3 pt-6 border-t">
            <Link
              href="/platform/dashboard"
              className="px-6 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Cancel
            </Link>
            <button
              type="submit"
              disabled={saving}
              className="flex items-center space-x-2 px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50"
            >
              {saving ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                  <span>Creating...</span>
                </>
              ) : (
                <>
                  <Save className="w-4 h-4" />
                  <span>Create Business & Admin</span>
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}